package com.agri.costtracker.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिंदी"),
    TELUGU("te", "Telugu", "తెలుగు"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ"),
    TAMIL("ta", "Tamil", "தமிழ்"),
    MARATHI("mr", "Marathi", "मराठी"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી"),
    PUNJABI("pa", "Punjabi", "ਪੰਜਾਬੀ")
}

data class AppStrings(
    // App Brand
    val appTitle: String,
    val appSubtitle: String,
    val languageLabel: String,
    val selectLanguage: String,

    // Navigation
    val navDashboard: String,
    val navFarmers: String,
    val navRates: String,
    val navHistory: String,

    // Common Actions
    val addFarmer: String,
    val newBooking: String,
    val save: String,
    val cancel: String,
    val close: String,
    val delete: String,
    val exportShare: String,
    val allFarmers: String,
    val allStatus: String,
    val unpaidOnly: String,
    val paid: String,
    val unpaid: String,
    val partial: String,
    val acres: String,
    val perAcre: String,

    // Partial Payment & Calculation
    val amountPaidLabel: String,
    val remainingBalance: String,
    val recordPayment: String,
    val enterPaymentAmount: String,
    val paymentDateLabel: String,
    val paymentRecordedSuccess: String,

    // Dashboard
    val dashboardSubtitle: String,
    val totalServicedLand: String,
    val droneSprayed: String,
    val harvestedCut: String,
    val totalBilled: String,
    val totalCollected: String,
    val pendingDue: String,
    val droneRate: String,
    val cuttingRate: String,
    val perAcreSetting: String,
    val recentDeployments: String,
    val viewAll: String,
    val generateFiscalReport: String,

    // Farmers Directory
    val farmersDirectoryTitle: String,
    val farmersDirectorySubtitle: String,
    val registerNewFarmer: String,
    val totalRegistered: String,
    val totalServiced: String,
    val pendingBills: String,
    val noFarmersYet: String,
    val servicedLand: String,
    val viewStatement: String,
    val farmerAccountStatement: String,
    val itemizedHistory: String,
    val totalBilledAmount: String,
    val totalPaidAmount: String,
    val pendingBalanceDue: String,

    // Add Farmer Dialog
    val clientRegistration: String,
    val farmerFullName: String,
    val mobileNumber: String,
    val villageSector: String,
    val totalFarmLand: String,
    val cropsNotes: String,
    val nameMandatory: String,
    val mobileMandatory: String,

    // Add Booking Dialog
    val newServiceRental: String,
    val bookDroneMachine: String,
    val selectRegisteredFarmer: String,
    val serviceType: String,
    val droneSpraying: String,
    val cuttingMachine: String,
    val totalAcres: String,
    val ratePerAcreInput: String,
    val advancePaidOptional: String,
    val calculatedTotalBill: String,
    val fieldLocation: String,
    val paymentStatus: String,
    val saveBooking: String,
    val selectFarmerError: String,

    // Rates Screen
    val configuration: String,
    val serviceRates: String,
    val ratesSubtitle: String,
    val sprayingRateTitle: String,
    val sprayingRateSub: String,
    val cuttingRateTitle: String,
    val cuttingRateSub: String,
    val updateRates: String,
    val costPerAcre: String,

    // History Screen
    val serviceHistory: String,
    val bookingsFeed: String,
    val noBookingsFound: String
)

val EnglishStrings = AppStrings(
    appTitle = "AGRI SERVICES",
    appSubtitle = "Drone & Harvester Rentals",
    languageLabel = "Language",
    selectLanguage = "Select Language",
    navDashboard = "DASHBOARD",
    navFarmers = "FARMERS",
    navRates = "RATES",
    navHistory = "HISTORY",
    addFarmer = "Farmer",
    newBooking = "New Booking",
    save = "Save",
    cancel = "Cancel",
    close = "Close",
    delete = "Delete",
    exportShare = "Export / Share Statement",
    allFarmers = "All Farmers",
    allStatus = "All Status",
    unpaidOnly = "Unpaid / Partial Only",
    paid = "PAID",
    unpaid = "UNPAID",
    partial = "PARTIAL",
    acres = "Acres",
    perAcre = "Per Acre",
    amountPaidLabel = "Advance / Paid Amount (₹)",
    remainingBalance = "Remaining Balance Due",
    recordPayment = "+ Add Payment / Collect Cash",
    enterPaymentAmount = "Enter Received Payment (₹)",
    paymentDateLabel = "Payment Received Date",
    paymentRecordedSuccess = "Payment recorded successfully!",
    dashboardSubtitle = "Real-time overview of machinery deployments, drone spraying acreage, farmer billing, and collected payments.",
    totalServicedLand = "TOTAL SERVICED ACREAGE (SEASON 2024)",
    droneSprayed = "DRONE SPRAYED",
    harvestedCut = "HARVESTED / CUT",
    totalBilled = "TOTAL BILLED",
    totalCollected = "TOTAL COLLECTED",
    pendingDue = "PENDING DUE",
    droneRate = "DRONE RATE",
    cuttingRate = "CUTTING RATE",
    perAcreSetting = "Per Acre Setting",
    recentDeployments = "Recent Deployments",
    viewAll = "View All",
    generateFiscalReport = "Generate Business Fiscal Report",
    farmersDirectoryTitle = "Registered Farmers",
    farmersDirectorySubtitle = "Manage your farmer network, monitor drone spraying & harvester acreage, and track individual payments.",
    registerNewFarmer = "+ Register New Farmer",
    totalRegistered = "TOTAL REGISTERED",
    totalServiced = "TOTAL SERVICED",
    pendingBills = "PENDING BILLS",
    noFarmersYet = "No farmers registered yet.",
    servicedLand = "SERVICED LAND",
    viewStatement = "View Statement",
    farmerAccountStatement = "FARMER ACCOUNT STATEMENT",
    itemizedHistory = "ITEMIZED SERVICE HISTORY",
    totalBilledAmount = "Total Billed Amount:",
    totalPaidAmount = "Total Amount Paid:",
    pendingBalanceDue = "Pending Balance Due:",
    clientRegistration = "CLIENT REGISTRATION",
    farmerFullName = "Farmer Full Name *",
    mobileNumber = "Mobile Number *",
    villageSector = "Village / Sector",
    totalFarmLand = "Total Farm Land (Acres)",
    cropsNotes = "Crops / Client Notes (Optional)",
    nameMandatory = "Farmer name is mandatory",
    mobileMandatory = "Mobile number is mandatory",
    newServiceRental = "NEW SERVICE RENTAL",
    bookDroneMachine = "Book Drone / Machine",
    selectRegisteredFarmer = "SELECT REGISTERED FARMER *",
    serviceType = "SERVICE TYPE",
    droneSpraying = "🚁 Drone Spraying",
    cuttingMachine = "🚜 Cutting Machine",
    totalAcres = "Total Acres *",
    ratePerAcreInput = "Rate/Acre (₹) *",
    advancePaidOptional = "Advance / Initial Payment (₹)",
    calculatedTotalBill = "CALCULATED TOTAL BILL",
    fieldLocation = "Field Location / Village",
    paymentStatus = "PAYMENT / BILLING STATUS",
    saveBooking = "Save Service Booking",
    selectFarmerError = "Please select or add a farmer",
    configuration = "CONFIGURATION",
    serviceRates = "Service Rates",
    ratesSubtitle = "Adjust your operational rental costs per acre for precision financial forecasting.",
    sprayingRateTitle = "Spraying",
    sprayingRateSub = "PESTICIDES & FERTILIZERS",
    cuttingRateTitle = "Crop Cutting",
    cuttingRateSub = "HARVESTING & THRESHING",
    updateRates = "Update Rates",
    costPerAcre = "COST PER ACRE",
    serviceHistory = "Service History",
    bookingsFeed = "Bookings Feed",
    noBookingsFound = "No matching rental bookings found."
)

val HindiStrings = AppStrings(
    appTitle = "कृषि सेवाएं",
    appSubtitle = "ड्रोन और हार्वेस्टर किराया",
    languageLabel = "भाषा",
    selectLanguage = "भाषा चुनें",
    navDashboard = "डैशबोर्ड",
    navFarmers = "किसान",
    navRates = "दरें",
    navHistory = "इतिहास",
    addFarmer = "+ किसान",
    newBooking = "नई बुकिंग",
    save = "सहेजें",
    cancel = "रद्द करें",
    close = "बंद करें",
    delete = "हटाएं",
    exportShare = "स्टेटमेंट साझा करें",
    allFarmers = "सभी किसान",
    allStatus = "सभी स्थिति",
    unpaidOnly = "बकाया / आंशिक",
    paid = "पूर्ण भुगतान",
    unpaid = "बकाया",
    partial = "आंशिक भुगतान",
    acres = "एकड़",
    perAcre = "प्रति एकड़",
    amountPaidLabel = "प्राप्त / अग्रिम राशि (₹)",
    remainingBalance = "शेष बकाया राशि",
    recordPayment = "+ भुगतान जमा करें / नकद लें",
    enterPaymentAmount = "जमा की जाने वाली राशि (₹)",
    paymentDateLabel = "भुगतान प्राप्त करने की तिथि",
    paymentRecordedSuccess = "भुगतान सफलतापूर्वक दर्ज किया गया!",
    dashboardSubtitle = "ड्रोन छिड़काव, हार्वेस्टर कटाई, किसान बिलिंग, प्राप्त भुगतान और बकाया राशि का विवरण।",
    totalServicedLand = "कुल सेवा एकड़ (सीजन 2024)",
    droneSprayed = "ड्रोन छिड़काव",
    harvestedCut = "कटाई / हार्वेस्टर",
    totalBilled = "कुल बिल राशि",
    totalCollected = "कुल प्राप्त राशि",
    pendingDue = "कुल बकाया",
    droneRate = "ड्रोन दर",
    cuttingRate = "कटाई दर",
    perAcreSetting = "प्रति एकड़ दर",
    recentDeployments = "हाल की सेवाएं",
    viewAll = "सभी देखें",
    generateFiscalReport = "व्यापार रिपोर्ट बनाएं",
    farmersDirectoryTitle = "पंजीकृत किसान",
    farmersDirectorySubtitle = "अपने किसान नेटवर्क को प्रबंधित करें, आंशिक और कुल भुगतानों का हिसाब रखें।",
    registerNewFarmer = "+ नया किसान जोड़ें",
    totalRegistered = "कुल पंजीकृत",
    totalServiced = "कुल सेवा क्षेत्र",
    pendingBills = "बकाया बिल",
    noFarmersYet = "अभी तक कोई किसान पंजीकृत नहीं है।",
    servicedLand = "सेवा एकड़",
    viewStatement = "खाता विवरण",
    farmerAccountStatement = "किसान खाता विवरण",
    itemizedHistory = "सेवा इतिहास विवरण",
    totalBilledAmount = "कुल बिल राशि:",
    totalPaidAmount = "कुल प्राप्त राशि:",
    pendingBalanceDue = "शेष बकाया राशि:",
    clientRegistration = "किसान पंजीकरण",
    farmerFullName = "किसान का पूरा नाम *",
    mobileNumber = "मोबाइल नंबर *",
    villageSector = "गांव / क्षेत्र",
    totalFarmLand = "कुल खेत जमीन (एकड़)",
    cropsNotes = "फसल / टिप्पणी (वैकल्पिक)",
    nameMandatory = "किसान का नाम अनिवार्य है",
    mobileMandatory = "मोबाइल नंबर अनिवार्य है",
    newServiceRental = "नई सेवा बुकिंग",
    bookDroneMachine = "ड्रोन / मशीन बुक करें",
    selectRegisteredFarmer = "किसान चुनें *",
    serviceType = "सेवा का प्रकार",
    droneSpraying = "🚁 ड्रोन छिड़काव",
    cuttingMachine = "🚜 कटाई मशीन",
    totalAcres = "कुल एकड़ *",
    ratePerAcreInput = "दर/एकड़ (₹) *",
    advancePaidOptional = "अग्रिम / प्राप्त राशि (₹)",
    calculatedTotalBill = "कुल गणना बिल राशि",
    fieldLocation = "खेत का स्थान / गांव",
    paymentStatus = "भुगतान स्थिति",
    saveBooking = "बुकिंग सहेजें",
    selectFarmerError = "कृपया एक किसान चुनें या जोड़ें",
    configuration = "दर विन्यास",
    serviceRates = "सेवा दरें",
    ratesSubtitle = "सटीक बिलिंग के लिए प्रति एकड़ अपनी परिचालन दरें निर्धारित करें।",
    sprayingRateTitle = "ड्रोन छिड़काव",
    sprayingRateSub = "कीटनाशक और उर्वरक",
    cuttingRateTitle = "फसल कटाई",
    cuttingRateSub = "हार्वेस्टर और थ्रेशिंग",
    updateRates = "दरें अपडेट करें",
    costPerAcre = "प्रति एकड़ लागत",
    serviceHistory = "सेवा इतिहास",
    bookingsFeed = "बुकिंग सूची",
    noBookingsFound = "कोई बुकिंग नहीं मिली।"
)

val TeluguStrings = AppStrings(
    appTitle = "వ్యవసాయ సేవలు",
    appSubtitle = "డ్రోన్ & హార్వెస్టర్ అద్దె",
    languageLabel = "భాష",
    selectLanguage = "భాషను ఎంచుకోండి",
    navDashboard = "డ్యాష్‌బోర్డ్",
    navFarmers = "రైతులు",
    navRates = "ధరలు",
    navHistory = "చరిత్ర",
    addFarmer = "+ రైతు",
    newBooking = "కొత్త బుకింగ్",
    save = "సేవ్ చేయండి",
    cancel = "రద్దు చేయండి",
    close = "మూసివేయండి",
    delete = "తొలగించండి",
    exportShare = "స్టేట్‌మెంట్ షేర్ చేయండి",
    allFarmers = "అందరు రైతులు",
    allStatus = "అన్ని రకాలు",
    unpaidOnly = "బాకీ / పాక్షిక మాత్రమే",
    paid = "పూర్తి చెల్లింపు",
    unpaid = "బాకీ ఉంది",
    partial = "కొంత చెల్లించారు",
    acres = "ఎకరాలు",
    perAcre = "ఎకరానికి",
    amountPaidLabel = "చెల్లించిన / అడ్వాన్స్ మొత్తం (₹)",
    remainingBalance = "మిగిలిన బాకీ మొత్తం",
    recordPayment = "+ చెల్లింపు నమోదు చేయండి",
    enterPaymentAmount = "వచ్చిన మొత్తం నమోదు చేయండి (₹)",
    paymentDateLabel = "డబ్బులు అందిన తేదీ",
    paymentRecordedSuccess = "చెల్లింపు విజయవంతంగా నమోదైంది!",
    dashboardSubtitle = "డ్రోన్ స్ప్రేయింగ్, కోత యంత్రం పనితీరు, వచ్చిన డబ్బు మరియు మిగిలిన బాకీ వివరాలు.",
    totalServicedLand = "మొత్తం సేవా భూమి (సీజన్ 2024)",
    droneSprayed = "డ్రోన్ స్ప్రే",
    harvestedCut = "కోత యంత్రం",
    totalBilled = "మొత్తం బిల్లు",
    totalCollected = "వచ్చిన మొత్తం",
    pendingDue = "బాకీ ఉన్న మొత్తం",
    droneRate = "డ్రోన్ ధర",
    cuttingRate = "కోత ధర",
    perAcreSetting = "ఎకరానికి ధర",
    recentDeployments = "ఇటీవలి సేవలు",
    viewAll = "అన్నీ చూడండి",
    generateFiscalReport = "వ్యాపార నివేదిక",
    farmersDirectoryTitle = "నమోదైన రైతులు",
    farmersDirectorySubtitle = "రైతుల జాబితా, చెల్లించిన మొత్తం మరియు బాకీ లెక్కలను నిర్వహించండి.",
    registerNewFarmer = "+ కొత్త రైతు నమోదు",
    totalRegistered = "మొత్తం రైతులు",
    totalServiced = "మొత్తం ఎకరాలు",
    pendingBills = "బాకీ బిల్లులు",
    noFarmersYet = "ఇంకా రైతులు నమోదు కాలేదు.",
    servicedLand = "సేవ చేసిన భూమి",
    viewStatement = "ఖాతా చూడు",
    farmerAccountStatement = "రైతు ఖాతా స్టేట్‌మెంట్",
    itemizedHistory = "సేవా వివరాల చరిత్ర",
    totalBilledAmount = "మొత్తం బిల్లు:",
    totalPaidAmount = "ఇప్పటివరకు చెల్లించినది:",
    pendingBalanceDue = "మిగిలిన బాకీ:",
    clientRegistration = "రైతు నమోదు",
    farmerFullName = "రైతు పూర్తి పేరు *",
    mobileNumber = "మొబైల్ నంబర్ *",
    villageSector = "గ్రామం / ప్రాంతం",
    totalFarmLand = "మొత్తం పొలం భూమి (ఎకరాలు)",
    cropsNotes = "పంటలు / గమనికలు",
    nameMandatory = "రైతు పేరు తప్పనిసరి",
    mobileMandatory = "మొబైల్ నంబర్ తప్పనిసరి",
    newServiceRental = "కొత్త సర్వీస్ అద్దె",
    bookDroneMachine = "డ్రోన్ / యంత్రం బుకింగ్",
    selectRegisteredFarmer = "రైతును ఎంచుకోండి *",
    serviceType = "సేవ రకం",
    droneSpraying = "🚁 డ్రోన్ స్ప్రేయింగ్",
    cuttingMachine = "🚜 కోత యంత్రం",
    totalAcres = "మొత్తం ఎకరాలు *",
    ratePerAcreInput = "ధర/ఎకరానికి (₹) *",
    advancePaidOptional = "అడ్వాన్స్ / అందిన మొత్తం (₹)",
    calculatedTotalBill = "లెక్కించిన మొత్తం బిల్లు",
    fieldLocation = "పొలం స్థలం / గ్రామం",
    paymentStatus = "చెల్లింపు స్థితి",
    saveBooking = "బుకింగ్ సేవ్ చేయండి",
    selectFarmerError = "దయచేసి రైతును ఎంచుకోండి",
    configuration = "ధరల అమరిక",
    serviceRates = "సేవ ధరలు",
    ratesSubtitle = "ఖచ్చితమైన బిల్లింగ్ కోసం ఎకరానికి అద్దె ధరలను సెట్ చేయండి.",
    sprayingRateTitle = "డ్రోన్ స్ప్రేయింగ్",
    sprayingRateSub = "మందులు & ఎరువులు",
    cuttingRateTitle = "పంట కోత",
    cuttingRateSub = "కోత & నూర్పిడి",
    updateRates = "ధరలు మార్చండి",
    costPerAcre = "ఎకరానికి ధర",
    serviceHistory = "సేవా చరిత్ర",
    bookingsFeed = "బుకింగ్స్ జాబితా",
    noBookingsFound = "బుకింగ్‌లు ఏవీ లేవు."
)

val KannadaStrings = AppStrings(
    appTitle = "ಕೃಷಿ ಸೇವೆಗಳು",
    appSubtitle = "ಡ್ರೋನ್ & ಹಾರ್ವೆಸ್ಟರ್ ಬಾಡಿಗೆ",
    languageLabel = "ಭಾಷೆ",
    selectLanguage = "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    navDashboard = "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navFarmers = "ರೈತರು",
    navRates = "ದರಗಳು",
    navHistory = "ಇತಿಹಾಸ",
    addFarmer = "+ ರೈತ",
    newBooking = "ಹೊಸ ಬುಕಿಂಗ್",
    save = "ಉಳಿಸಿ",
    cancel = "ರದ್ದುಮಾಡಿ",
    close = "ಮುಚ್ಚಿ",
    delete = "ಅಳಿಸಿ",
    exportShare = "ಸ್ಟೇಟ್‌ಮೆಂಟ್ ಹಂಚಿಕೊಳ್ಳಿ",
    allFarmers = "ಎಲ್ಲಾ ರೈತರು",
    allStatus = "ಎಲ್ಲಾ ಸ್ಥಿತಿ",
    unpaidOnly = "ಬಾಕಿ / ಭಾಗಶಃ ಮಾತ್ರ",
    paid = "ಪೂರ್ಣ ಪಾವತಿ",
    unpaid = "ಬಾಕಿ ಇದೆ",
    partial = "ಭಾಗಶಃ ಪಾವತಿ",
    acres = "ಎಕರೆ",
    perAcre = "ಪ್ರತಿ ಎಕರೆಗೆ",
    amountPaidLabel = "ಪಾವತಿಸಿದ / ಮುಂಗಡ ಮೊತ್ತ (₹)",
    remainingBalance = "ಉಳಿದ ಬಾಕಿ ಮೊತ್ತ",
    recordPayment = "+ ಪಾವತಿ ನಮೂದಿಸಿ",
    enterPaymentAmount = "ಸ್ವೀಕರಿಸಿದ ಮೊತ್ತ (₹)",
    paymentDateLabel = "ಹಣ ಸ್ವೀಕರಿಸಿದ ದಿನಾಂಕ",
    paymentRecordedSuccess = "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ!",
    dashboardSubtitle = "ಡ್ರೋನ್ ಸಿಂಪಡಣೆ, ಕೊಯ್ಲು ಯಂತ್ರದ ಬಳಕೆ, ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಬಾಕಿ ವಿವರಗಳು.",
    totalServicedLand = "ಒಟ್ಟು ಸೇವಾ ಭೂಮಿ (2024)",
    droneSprayed = "ಡ್ರೋನ್ ಸಿಂಪಡಣೆ",
    harvestedCut = "ಕೊಯ್ಲು ಯಂತ್ರ",
    totalBilled = "ಒಟ್ಟು ಬಿಲ್",
    totalCollected = "ಒಟ್ಟು ಸಂಗ್ರಹಿಸಿದ ಮೊತ್ತ",
    pendingDue = "ಬಾಕಿ ಮೊತ್ತ",
    droneRate = "ಡ್ರೋನ್ ದರ",
    cuttingRate = "ಕೊಯ್ಲು ದರ",
    perAcreSetting = "ಪ್ರತಿ ಎಕರೆ ದರ",
    recentDeployments = "ಇತ್ತೀಚಿನ ಸೇವೆಗಳು",
    viewAll = "ಎಲ್ಲಾ ನೋಡಿ",
    generateFiscalReport = "ವ್ಯಾಪಾರ ವರದಿ",
    farmersDirectoryTitle = "ನೋಂದಾಯಿತ ರೈತರು",
    farmersDirectorySubtitle = "ರೈತರ ಪಟ್ಟಿ, ಡ್ರೋನ್ ಮತ್ತು ಯಂತ್ರಗಳ ಲೆಕ್ಕಪತ್ರವನ್ನು ನಿರ್ವಹಿಸಿ.",
    registerNewFarmer = "+ ಹೊಸ ರೈತ ನೋಂದಣಿ",
    totalRegistered = "ಒಟ್ಟು ರೈತರು",
    totalServiced = "ಒಟ್ಟು ಎಕರೆ",
    pendingBills = "ಬಾಕಿ ಬಿಲ್‌ಗಳು",
    noFarmersYet = "ಯಾವುದೇ ರೈತರು ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿಲ್ಲ.",
    servicedLand = "ಸೇವೆ ಸಲ್ಲಿಸಿದ ಭೂಮಿ",
    viewStatement = "ಖಾತೆ ವಿವರ",
    farmerAccountStatement = "ರೈತರ ಖಾತೆ ವಿವರ",
    itemizedHistory = "ಸೇವಾ ಇತಿಹಾಸ",
    totalBilledAmount = "ಒಟ್ಟು ಬಿಲ್ ಮೊತ್ತ:",
    totalPaidAmount = "ಪಾವತಿಸಿದ ಒಟ್ಟು ಮೊತ್ತ:",
    pendingBalanceDue = "ಉಳಿದ ಬಾಕಿ ಮೊತ್ತ:",
    clientRegistration = "ರೈತ ನೋಂದಣಿ",
    farmerFullName = "ರೈತರ ಪೂರ್ಣ ಹೆಸರು *",
    mobileNumber = "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *",
    villageSector = "ಗ್ರಾಮ / ಪ್ರದೇಶ",
    totalFarmLand = "ಒಟ್ಟು ಜಮೀನು (ಎಕರೆ)",
    cropsNotes = "ಬೆಳೆಗಳು / ಟಿಪ್ಪಣಿಗಳು",
    nameMandatory = "ರೈತರ ಹೆಸರು ಕಡ್ಡಾಯ",
    mobileMandatory = "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಕಡ್ಡಾಯ",
    newServiceRental = "ಹೊಸ ಸೇವಾ ಬಾಡಿಗೆ",
    bookDroneMachine = "ಡ್ರೋನ್ / ಯಂತ್ರ ಬುಕ್ ಮಾಡಿ",
    selectRegisteredFarmer = "ರೈತರನ್ನು ಆಯ್ಕೆಮಾಡಿ *",
    serviceType = "ಸೇವೆಯ ಪ್ರಕಾರ",
    droneSpraying = "🚁 ಡ್ರೋನ್ ಸಿಂಪಡಣೆ",
    cuttingMachine = "🚜 ಕೊಯ್ಲು ಯಂತ್ರ",
    totalAcres = "ಒಟ್ಟು ಎಕರೆ *",
    ratePerAcreInput = "ದರ/ಎಕರೆಗೆ (₹) *",
    advancePaidOptional = "ಮುಂಗಡ / ಪಾವತಿಸಿದ ಮೊತ್ತ (₹)",
    calculatedTotalBill = "ಲೆಕ್ಕಹಾಕಿದ ಒಟ್ಟು ಬಿಲ್",
    fieldLocation = "ಜಮೀನಿನ ಸ್ಥಳ / ಗ್ರಾಮ",
    paymentStatus = "ಪಾವತಿ ಸ್ಥಿತಿ",
    saveBooking = "ಬುಕಿಂಗ್ ಉಳಿಸಿ",
    selectFarmerError = "ದಯವಿಟ್ಟು ರೈತರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    configuration = "ದರ ಸಂರಚನೆ",
    serviceRates = "ಸೇವಾ ದರಗಳು",
    ratesSubtitle = "ನಿಖರ ಬಿಲ್ಲಿಂಗ್‌ಗಾಗಿ ಪ್ರತಿ ಎಕರೆಗೆ ಬಾಡಿಗೆ ದರಗಳನ್ನು ಹೊಂದಿಸಿ.",
    sprayingRateTitle = "ಡ್ರೋನ್ ಸಿಂಪಡಣೆ",
    sprayingRateSub = "ಕೀಟನಾಶಕಗಳು ಮತ್ತು ರಸಗೊಬ್ಬರಗಳು",
    cuttingRateTitle = "ಬೆಳೆ ಕೊಯ್ಲು",
    cuttingRateSub = "ಕೊಯ್ಲು ಮತ್ತು ಒಕ್ಕಣೆ",
    updateRates = "ದರಗಳನ್ನು ನವೀಕರಿಸಿ",
    costPerAcre = "ಪ್ರತಿ ಎಕರೆ ವೆಚ್ಚ",
    serviceHistory = "ಸೇವಾ ಇತಿಹಾಸ",
    bookingsFeed = "ಬುಕಿಂಗ್ ಪಟ್ಟಿ",
    noBookingsFound = "ಯಾವುದೇ ಬುಕಿಂಗ್ ಕಂಡುಬಂದಿಲ್ಲ."
)

val TamilStrings = AppStrings(
    appTitle = "விவசாய சேவைகள்",
    appSubtitle = "ட்ரோன் & அறுவடை இயந்திர வாடகை",
    languageLabel = "மொழி",
    selectLanguage = "மொழியைத் தேர்ந்தெடுக்கவும்",
    navDashboard = "டாஷ்போர்டு",
    navFarmers = "விவசாயிகள்",
    navRates = "கட்டணங்கள்",
    navHistory = "வரலாறு",
    addFarmer = "+ விவசாயி",
    newBooking = "புதிய பதிவு",
    save = "சேமிக்க",
    cancel = "ரத்து செய்",
    close = "மூடு",
    delete = "நீக்கு",
    exportShare = "அறிக்கையைப் பகிரவும்",
    allFarmers = "அனைத்து விவசாயிகள்",
    allStatus = "அனைத்து நிலைகளும்",
    unpaidOnly = "நிலுவை / பகுதி மட்டும்",
    paid = "முழு கட்டணம்",
    unpaid = "நிலுவை",
    partial = "பகுதி செலுத்தியது",
    acres = "ஏக்கர்",
    perAcre = "ஏக்கருக்கு",
    amountPaidLabel = "செலுத்திய / முன்பணம் (₹)",
    remainingBalance = "மீதமுள்ள நிலுவைத் தொகை",
    recordPayment = "+ கட்டணம் பதிவு செய்",
    enterPaymentAmount = "பெறப்பட்ட தொகை (₹)",
    paymentDateLabel = "கட்டணம் பெறப்பட்ட தேதி",
    paymentRecordedSuccess = "கட்டணம் வெற்றிகரமாக பதிவானது!",
    dashboardSubtitle = "ட்ரோன் தெளித்தல், அறுவடை இயந்திர பயன்பாடு மற்றும் பில்லிங் விவரங்கள்.",
    totalServicedLand = "மொத்த சேவை நிலம் (சீசன் 2024)",
    droneSprayed = "ட்ரோன் தெளிப்பு",
    harvestedCut = "அறுவடை இயந்திரம்",
    totalBilled = "மொத்த பில்",
    totalCollected = "மொத்த வசூல்",
    pendingDue = "நிலுவைத் தொகை",
    droneRate = "ட்ரோன் கட்டணம்",
    cuttingRate = "அறுவடை கட்டணம்",
    perAcreSetting = "ஏக்கர் கட்டணம்",
    recentDeployments = "சமீபத்திய சேவைகள்",
    viewAll = "அனைத்தையும் பார்க்க",
    generateFiscalReport = "வணிக அறிக்கை",
    farmersDirectoryTitle = "பதிவுசெய்த விவசாயிகள்",
    farmersDirectorySubtitle = "விவசாயிகள் பட்டியல் மற்றும் கணக்கு விவரங்களை நிர்வகிக்கவும்.",
    registerNewFarmer = "+ புதிய விவசாயி பதிவு",
    totalRegistered = "மொத்த விவசாயிகள்",
    totalServiced = "மொத்த ஏக்கர்",
    pendingBills = "நிலுவை பில்கள்",
    noFarmersYet = "விவசாயிகள் யாரும் பதிவு செய்யப்படவில்லை.",
    servicedLand = "சேவை செய்யப்பட்ட நிலம்",
    viewStatement = "கணக்கு அறிக்கை",
    farmerAccountStatement = "விவசாயி கணக்கு அறிக்கை",
    itemizedHistory = "சேவை வரலாறு",
    totalBilledAmount = "மொத்த பில் தொகை:",
    totalPaidAmount = "செலுத்தப்பட்ட தொகை:",
    pendingBalanceDue = "மீதமுள்ள நிலுவைத் தொகை:",
    clientRegistration = "விவசாயி பதிவு",
    farmerFullName = "விவசாயி முழுப் பெயர் *",
    mobileNumber = "கைபேசி எண் *",
    villageSector = "கிராமம் / பகுதி",
    totalFarmLand = "மொத்த நிலம் (ஏக்கர்)",
    cropsNotes = "பயிர்கள் / குறிப்புகள்",
    nameMandatory = "விவசாயி பெயர் கட்டாயம்",
    mobileMandatory = "கைபேசி எண் கட்டாயம்",
    newServiceRental = "புதிய சேவை வாடகை",
    bookDroneMachine = "ட்ரோன் / இயந்திரம் பதிவு",
    selectRegisteredFarmer = "விவசாயியைத் தேர்ந்தெடுக்கவும் *",
    serviceType = "சேவை வகை",
    droneSpraying = "🚁 ட்ரோன் தெளித்தல்",
    cuttingMachine = "🚜 அறுவடை இயந்திரம்",
    totalAcres = "மொத்த ஏக்கர் *",
    ratePerAcreInput = "ஏக்கர் கட்டணம் (₹) *",
    advancePaidOptional = "முன்பணம் / செலுத்திய தொகை (₹)",
    calculatedTotalBill = "கணக்கிடப்பட்ட மொத்த பில்",
    fieldLocation = "வயல் இடம் / கிராமம்",
    paymentStatus = "கட்டண நிலை",
    saveBooking = "பதிவைச் சேமிக்கவும்",
    selectFarmerError = "விவசாயியைத் தேர்ந்தெடுக்கவும்",
    configuration = "கட்டண அமைப்பு",
    serviceRates = "சேவை கட்டணங்கள்",
    ratesSubtitle = "ஏக்கருக்கான வாடகைக் கட்டணங்களை அமைக்கவும்.",
    sprayingRateTitle = "ட்ரோன் தெளித்தல்",
    sprayingRateSub = "பூச்சிக்கொல்லி & உரம்",
    cuttingRateTitle = "பயிர் அறுவடை",
    cuttingRateSub = "அறுவடை & கதிர் அடித்தல்",
    updateRates = "கட்டணங்களைப் புதுப்பிக்கவும்",
    costPerAcre = "ஏக்கருக்கு செலவு",
    serviceHistory = "சேவை வரலாறு",
    bookingsFeed = "பதிவுகள் பட்டியல்",
    noBookingsFound = "பதிவுகள் எதுவும் இல்லை."
)

val MarathiStrings = AppStrings(
    appTitle = "कृषी सेवा",
    appSubtitle = "ड्रोन आणि हार्वेस्टर भाडेतत्त्व",
    languageLabel = "भाषा",
    selectLanguage = "भाषा निवडा",
    navDashboard = "डॅशबोर्ड",
    navFarmers = "शेतकरी",
    navRates = "दर",
    navHistory = "इतिहास",
    addFarmer = "+ शेतकरी",
    newBooking = "नवीन बुकिंग",
    save = "जतन करा",
    cancel = "रद्द करा",
    close = "बंद करा",
    delete = "हटवा",
    exportShare = "स्टेटमेंट शेअर करा",
    allFarmers = "सर्व शेतकरी",
    allStatus = "सर्व स्थिती",
    unpaidOnly = "बाकी / अर्धवट फक्त",
    paid = "पूर्ण भरले",
    unpaid = "बाकी",
    partial = "अर्धवट भरले",
    acres = "एकर",
    perAcre = "प्रति एकर",
    amountPaidLabel = "जमा / आगाऊ रक्कम (₹)",
    remainingBalance = "उर्वरित बाकी रक्कम",
    recordPayment = "+ पेमेंट जमा करा",
    enterPaymentAmount = "मिळालेली रक्कम (₹)",
    paymentDateLabel = "पेमेंट मिळाल्याची तारीख",
    paymentRecordedSuccess = "पेमेंट यशस्वीरित्या नोंदवले!",
    dashboardSubtitle = "ड्रोन फवारणी, हार्वेस्टर कापणी, शेतकरी बिलिंग आणि बाकी रकमेचा तपशील.",
    totalServicedLand = "एकूण सेवा क्षेत्र (हंगाम 2024)",
    droneSprayed = "ड्रोन फवारणी",
    harvestedCut = "कापणी / हार्वेस्टर",
    totalBilled = "एकूण बिल",
    totalCollected = "एकूण जमा रक्कम",
    pendingDue = "बाकी रक्कम",
    droneRate = "ड्रोन दर",
    cuttingRate = "कापणी दर",
    perAcreSetting = "प्रति एकर दर",
    recentDeployments = "अलीकडील सेवा",
    viewAll = "सर्व पहा",
    generateFiscalReport = "व्यवसाय अहवाल",
    farmersDirectoryTitle = "नोंदणीकृत शेतकरी",
    farmersDirectorySubtitle = "शेतकरी नेटवर्क व्यवस्थापित करा आणि खाते स्टेटमेंट पहा.",
    registerNewFarmer = "+ नवीन शेतकरी जोडा",
    totalRegistered = "एकूण शेतकरी",
    totalServiced = "एकूण एकर",
    pendingBills = "बाकी बिले",
    noFarmersYet = "अद्याप कोणतेही शेतकरी नोंदणीकृत नाहीत.",
    servicedLand = "सेवा क्षेत्र",
    viewStatement = "खाते विवरण",
    farmerAccountStatement = "शेतकरी खाते स्टेटमेंट",
    itemizedHistory = "सेवा तपशील इतिहास",
    totalBilledAmount = "एकूण बिल रक्कम:",
    totalPaidAmount = "एकूण भरलेली रक्कम:",
    pendingBalanceDue = "उर्वरित बाकी रक्कम:",
    clientRegistration = "शेतकरी नोंदणी",
    farmerFullName = "शेतकऱ्याचे पूर्ण नाव *",
    mobileNumber = "मोबाईल नंबर *",
    villageSector = "गाव / परिसर",
    totalFarmLand = "एकूण शेतजमीन (एकर)",
    cropsNotes = "पिके / टिपा (पर्यायी)",
    nameMandatory = "शेतकऱ्याचे नाव आवश्यक आहे",
    mobileMandatory = "मोबाईल नंबर आवश्यक आहे",
    newServiceRental = "नवीन सेवा भाडे",
    bookDroneMachine = "ड्रोन / मशीन बुक करा",
    selectRegisteredFarmer = "शेतकरी निवडा *",
    serviceType = "सेवेचा प्रकार",
    droneSpraying = "🚁 ड्रोन फवारणी",
    cuttingMachine = "🚜 कापणी मशीन",
    totalAcres = "एकूण एकर *",
    ratePerAcreInput = "दर/एकर (₹) *",
    advancePaidOptional = "आगाऊ / मिळालेली रक्कम (₹)",
    calculatedTotalBill = "एकूण बिल रक्कम",
    fieldLocation = "शेताचे ठिकाण / गाव",
    paymentStatus = "पेमेंट स्थिती",
    saveBooking = "बुकिंग जतन करा",
    selectFarmerError = "कृपया शेतकरी निवडा",
    configuration = "दर संरचना",
    serviceRates = "सेवा दर",
    ratesSubtitle = "अचूक बिलिंगसाठी प्रति एकर भाडे दर सेट करा.",
    sprayingRateTitle = "ड्रोन फवारणी",
    sprayingRateSub = "कीटकनाशके आणि खते",
    cuttingRateTitle = "पीक कापणी",
    cuttingRateSub = "हार्वेस्टर आणि मळणी",
    updateRates = "दर अपडेट करा",
    costPerAcre = "प्रति एकर खर्च",
    serviceHistory = "सेवा इतिहास",
    bookingsFeed = "बुकिंग यादी",
    noBookingsFound = "कोणतीही बुकिंग आढळली नाही."
)

val GujaratiStrings = AppStrings(
    appTitle = "કૃષિ સેવાઓ",
    appSubtitle = "ડ્રોન અને હાર્વેસ્ટર ભાડે",
    languageLabel = "ભાષા",
    selectLanguage = "ભાષા પસંદ કરો",
    navDashboard = "ડૅશબોર્ડ",
    navFarmers = "ખેડૂતો",
    navRates = "દર",
    navHistory = "ઇતિહાસ",
    addFarmer = "+ ખેડૂત",
    newBooking = "નવું બુકિંગ",
    save = "સાચવો",
    cancel = "રદ કરો",
    close = "બંધ કરો",
    delete = "કાઢી નાખો",
    exportShare = "સ્ટેટમેન્ટ શેર કરો",
    allFarmers = "બધા ખેડૂતો",
    allStatus = "બધી સ્થિતિ",
    unpaidOnly = "બાકી / અંશતઃ માત્ર",
    paid = "પૂર્ણ ચૂકવણી",
    unpaid = "બાકી",
    partial = "અંશતઃ ચૂકવેલ",
    acres = "એકર",
    perAcre = "પ્રતિ એકર",
    amountPaidLabel = "ચૂકવેલ / એડવાન્સ રકમ (₹)",
    remainingBalance = "બાકી રહેલ રકમ",
    recordPayment = "+ ચુકવણી ઉમેરો",
    enterPaymentAmount = "મળેલ રકમ દાખલ કરો (₹)",
    paymentDateLabel = "ચુકવણી મળ્યા તારીખ",
    paymentRecordedSuccess = "ચુકવણી સફળતાપૂર્વક નોંધાઈ!",
    dashboardSubtitle = "ડ્રોન સ્પ્રે, હાર્વેસ્ટર કામગીરી, બિલિંગ અને બાકી રકમની સંપૂર્ણ વિગતો.",
    totalServicedLand = "કુલ સેવા એકર (સીઝન 2024)",
    droneSprayed = "ડ્રોન સ્પ્રે",
    harvestedCut = "કાપણી / હાર્વેસ્ટર",
    totalBilled = "કુલ બિલ",
    totalCollected = "કુલ જમા રકમ",
    pendingDue = "બાકી રકમ",
    droneRate = "ડ્રોન દર",
    cuttingRate = "કાપણી દર",
    perAcreSetting = "પ્રતિ એકર દર",
    recentDeployments = "તાજેતરની સેવાઓ",
    viewAll = "બધા જુઓ",
    generateFiscalReport = "બિઝનેસ રિપોર્ટ બનાવો",
    farmersDirectoryTitle = "નોંધાયેલા ખેડૂતો",
    farmersDirectorySubtitle = "ખેડૂતોની યાદી અને ખાતાની વિગતો મેનેજ કરો.",
    registerNewFarmer = "+ નવો ખેડૂત ઉમેરો",
    totalRegistered = "કુલ ખેડૂતો",
    totalServiced = "કુલ એકર",
    pendingBills = "બાકી બિલ",
    noFarmersYet = "હજી સુધી કોઈ ખેડૂત નોંધાયેલા નથી.",
    servicedLand = "સેવા કરેલ જમીન",
    viewStatement = "ખાતાવહી જુઓ",
    farmerAccountStatement = "ખેડૂત ખાતાવહી સ્ટેટમેન્ટ",
    itemizedHistory = "સેવા ઇતિહાસ",
    totalBilledAmount = "કુલ બિલ રકમ:",
    totalPaidAmount = "કુલ ચૂકવેલ રકમ:",
    pendingBalanceDue = "બાકી રહેલ રકમ:",
    clientRegistration = "ખેડૂત નોંધણી",
    farmerFullName = "ખેડૂતનું પૂરું નામ *",
    mobileNumber = "મોબાઇલ નંબર *",
    villageSector = "ગામ / વિસ્તાર",
    totalFarmLand = "કુલ ખેતી જમીન (એકર)",
    cropsNotes = "પાક / નોંધ (વૈકલ્પિક)",
    nameMandatory = "ખેડૂતનું નામ ફરજિયાત છે",
    mobileMandatory = "મોબાઇલ નંબર ફરજિયાત છે",
    newServiceRental = "નવી સેવા ભાડું",
    bookDroneMachine = "ડ્રોન / મશીન બુક કરો",
    selectRegisteredFarmer = "ખેડૂત પસંદ કરો *",
    serviceType = "સેવાનો પ્રકાર",
    droneSpraying = "🚁 ડ્રોન છંટકાવ",
    cuttingMachine = "🚜 કાપણી મશીન",
    totalAcres = "કુલ એકર *",
    ratePerAcreInput = "દર/એકર (₹) *",
    advancePaidOptional = "એડવાન્સ / મળેલ રકમ (₹)",
    calculatedTotalBill = "કુલ ગણતરી કરેલ બિલ",
    fieldLocation = "ખેતરનું સ્થાન / ગામ",
    paymentStatus = "ચુકવણી સ્થિતિ",
    saveBooking = "બુકિંગ સાચવો",
    selectFarmerError = "કૃપા કરીને ખેડૂત પસંદ કરો",
    configuration = "દર સેટિંગ્સ",
    serviceRates = "સેવા દર",
    ratesSubtitle = "ચોક્કસ બિલિંગ માટે પ્રતિ એકર ભાડા દર સેટ કરો.",
    sprayingRateTitle = "ડ્રોન છંટકાવ",
    sprayingRateSub = "જંતુનાશકો અને ખાતરો",
    cuttingRateTitle = "પાક કાપણી",
    cuttingRateSub = "હાર્વેસ્ટર અને થ્રેશિંગ",
    updateRates = "દર અપડેટ કરો",
    costPerAcre = "પ્રતિ એકર ખર્ચ",
    serviceHistory = "સેવા ઇતિહાસ",
    bookingsFeed = "બુકિંગ ફીડ",
    noBookingsFound = "કોઈ બુકિંગ મળ્યું નથી."
)

val PunjabiStrings = AppStrings(
    appTitle = "ਖੇਤੀ ਸੇਵਾਵਾਂ",
    appSubtitle = "ਡਰੋਨ ਅਤੇ ਹਾਰਵੈਸਟਰ ਕਿਰਾਇਆ",
    languageLabel = "ਭਾਸ਼ਾ",
    selectLanguage = "ਭਾਸ਼ਾ ਚੁਣੋ",
    navDashboard = "ਡੈਸ਼ਬੋਰਡ",
    navFarmers = "ਕਿਸਾਨ",
    navRates = "ਰੇਟ",
    navHistory = "ਇਤਿਹਾਸ",
    addFarmer = "+ ਕਿਸਾਨ",
    newBooking = "ਨਵੀਂ ਬੁਕਿੰਗ",
    save = "ਸੰਭਾਲੋ",
    cancel = "ਰੱਦ ਕਰੋ",
    close = "ਬੰਦ ਕਰੋ",
    delete = "ਹਟਾਓ",
    exportShare = "ਸਟੇਟਮੈਂਟ ਸਾਂਝੀ ਕਰੋ",
    allFarmers = "ਸਾਰੇ ਕਿਸਾਨ",
    allStatus = "ਸਾਰੀ ਸਥਿਤੀ",
    unpaidOnly = "ਬਕਾਇਆ / ਅੰਸ਼ਕ ਸਿਰਫ਼",
    paid = "ਪੂਰਾ ਭੁਗਤਾਨ",
    unpaid = "ਬਕਾਇਆ",
    partial = "ਅੰਸ਼ਕ ਭੁਗਤਾਨ",
    acres = "ਏਕੜ",
    perAcre = "ਪ੍ਰਤੀ ਏਕੜ",
    amountPaidLabel = "ਪ੍ਰਾਪਤ / ਪੇਸ਼ਗੀ ਰਕਮ (₹)",
    remainingBalance = "ਬਾਕੀ ਬਕਾਇਆ ਰਕਮ",
    recordPayment = "+ ਭੁਗਤਾਨ ਦਰਜ ਕਰੋ",
    enterPaymentAmount = "ਮਿਲੀ ਰਕਮ ਦਰਜ ਕਰੋ (₹)",
    paymentDateLabel = "ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰਨ ਦੀ ਤਾਰੀਖ",
    paymentRecordedSuccess = "ਭੁਗਤਾਨ ਸਫ਼ਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋ ਗਿਆ!",
    dashboardSubtitle = "ਡਰੋਨ ਸਪਰੇਅ, ਹਾਰਵੈਸਟਰ ਕਟਾਈ, ਕਿਸਾਨ ਬਿਲਿੰਗ ਅਤੇ ਬਕਾਏ ਦੀ ਪੂਰੀ ਜਾਣਕਾਰੀ।",
    totalServicedLand = "ਕੁੱਲ ਸੇਵਾ ਖੇਤਰ (ਸੀਜ਼ਨ 2024)",
    droneSprayed = "ਡਰੋਨ ਸਪਰੇਅ",
    harvestedCut = "ਕਟਾਈ / ਹਾਰਵੈਸਟਰ",
    totalBilled = "ਕੁੱਲ ਬਿੱਲ",
    totalCollected = "ਕੁੱਲ ਇਕੱਠੀ ਰਕਮ",
    pendingDue = "ਬਕਾਇਆ ਰਕਮ",
    droneRate = "ਡਰੋਨ ਰੇਟ",
    cuttingRate = "ਕਟਾਈ ਰੇਟ",
    perAcreSetting = "ਪ੍ਰਤੀ ਏਕੜ ਰੇਟ",
    recentDeployments = "ਤਾਜ਼ਾ ਸੇਵਾਵਾਂ",
    viewAll = "ਸਾਰੇ ਵੇਖੋ",
    generateFiscalReport = "ਵਪਾਰ ਰਿਪੋਰਟ ਬਣਾਓ",
    farmersDirectoryTitle = "ਰਜਿਸਟਰਡ ਕਿਸਾਨ",
    farmersDirectorySubtitle = "ਕਿਸਾਨਾਂ ਦੀ ਸੂਚੀ, ਡਰੋਨ ਤੇ ਹਾਰਵੈਸਟਰ ਦਾ ਹਿਸਾਬ ਅਤੇ ਖਾਤਾ ਵੇਖੋ।",
    registerNewFarmer = "+ ਨਵਾਂ ਕਿਸਾਨ ਜੋੜੋ",
    totalRegistered = "ਕੁੱਲ ਕਿਸਾਨ",
    totalServiced = "ਕੁੱਲ ਏਕੜ",
    pendingBills = "ਬਕਾਇਆ ਬਿੱਲ",
    noFarmersYet = "ਕੋਈ ਕਿਸਾਨ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ।",
    servicedLand = "ਸੇਵਾ ਕੀਤਾ ਖੇਤਰ",
    viewStatement = "ਖਾਤਾ ਸਟੇਟਮੈਂਟ",
    farmerAccountStatement = "ਕਿਸਾਨ ਖਾਤਾ ਸਟੇਟਮੈਂਟ",
    itemizedHistory = "ਸੇਵਾ ਇਤਿਹਾਸ ਵੇਰਵਾ",
    totalBilledAmount = "ਕੁੱਲ ਬਿੱਲ ਰਕਮ:",
    totalPaidAmount = "ਕੁੱਲ ਪ੍ਰਾਪਤ ਰਕਮ:",
    pendingBalanceDue = "ਬਾਕੀ ਬਕਾਇਆ ਰਕਮ:",
    clientRegistration = "ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    farmerFullName = "ਕਿਸਾਨ ਦਾ ਪੂਰਾ ਨਾਮ *",
    mobileNumber = "ਮੋਬਾਈਲ ਨੰਬਰ *",
    villageSector = "ਪਿੰਡ / ਖੇਤਰ",
    totalFarmLand = "ਕੁੱਲ ਜ਼ਮੀਨ (ਏਕੜ)",
    cropsNotes = "ਫ਼ਸਲਾਂ / ਨੋਟਸ (ਵਿਕਲਪਿਕ)",
    nameMandatory = "ਕਿਸਾਨ ਦਾ ਨਾਮ ਜ਼ਰੂਰੀ ਹੈ",
    mobileMandatory = "ਮੋਬਾਈਲ ਨੰਬਰ ਜ਼ਰੂਰੀ ਹੈ",
    newServiceRental = "ਨਵੀਂ ਸੇਵਾ ਕਿਰਾਇਆ",
    bookDroneMachine = "ਡਰੋਨ / ਮਸ਼ੀਨ ਬੁੱਕ ਕਰੋ",
    selectRegisteredFarmer = "ਕਿਸਾਨ ਚੁਣੋ *",
    serviceType = "ਸੇਵਾ ਦੀ ਕਿਸਮ",
    droneSpraying = "🚁 ਡਰੋਨ ਸਪਰੇਅ",
    cuttingMachine = "🚜 ਕਟਾਈ ਮਸ਼ੀਨ",
    totalAcres = "ਕੁੱਲ ਏਕੜ *",
    ratePerAcreInput = "ਰੇਟ/ਏਕੜ (₹) *",
    advancePaidOptional = "ਪੇਸ਼ਗੀ / ਪ੍ਰਾਪਤ ਰਕਮ (₹)",
    calculatedTotalBill = "ਕੁੱਲ ਗਿਣਿਆ ਬਿੱਲ",
    fieldLocation = "ਖੇਤ ਦਾ ਸਥਾਨ / ਪਿੰਡ",
    paymentStatus = "ਭੁਗਤਾਨ ਸਥਿਤੀ",
    saveBooking = "ਬੁਕਿੰਗ ਸੰਭਾਲੋ",
    selectFarmerError = "ਕਿਰਪਾ ਕਰਕੇ ਕਿਸਾਨ ਚੁਣੋ",
    configuration = "ਰੇਟ ਸੈਟਿੰਗਜ਼",
    serviceRates = "ਸੇਵਾ ਰੇਟ",
    ratesSubtitle = "ਸਹੀ ਬਿਲਿੰਗ ਲਈ ਪ੍ਰਤੀ ਏਕੜ ਕਿਰਾਇਆ ਰੇਟ ਨਿਰਧਾਰਤ ਕਰੋ।",
    sprayingRateTitle = "ਡਰੋਨ ਸਪਰੇਅ",
    sprayingRateSub = "ਕੀਟਨਾਸ਼ਕ ਅਤੇ ਖਾਦਾਂ",
    cuttingRateTitle = "ਫ਼ਸਲ ਕਟਾਈ",
    cuttingRateSub = "ਹਾਰਵੈਸਟਰ ਅਤੇ ਗਹਾਈ",
    updateRates = "ਰੇਟ ਅਪਡੇਟ ਕਰੋ",
    costPerAcre = "ਪ੍ਰਤੀ ਏਕੜ ਲਾਗਤ",
    serviceHistory = "ਸੇਵਾ ਇਤਿਹਾਸ",
    bookingsFeed = "ਬੁਕਿੰਗ ਸੂਚੀ",
    noBookingsFound = "ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ ਮਿਲੀ।"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.HINDI -> HindiStrings
        AppLanguage.TELUGU -> TeluguStrings
        AppLanguage.KANNADA -> KannadaStrings
        AppLanguage.TAMIL -> TamilStrings
        AppLanguage.MARATHI -> MarathiStrings
        AppLanguage.GUJARATI -> GujaratiStrings
        AppLanguage.PUNJABI -> PunjabiStrings
    }
}
